up:
	./run.sh
exec:
	./php-exec.sh
php:
	./php-exec.sh
exec-nginx:
	./nginx-exec.sh
exec-db:
	./db-exec.sh
kill:
	docker-compose kill
logs:
	docker-compose logs -f
ps:
	docker-compose ps
rm:
	docker-compose rm
