parameters:

imports:
    - { resource: '../src/Common/Resources/config/services.yaml' }
    - { resource: '../src/Grabber/Resources/config/services.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $contactUsEmail: '%env(MAILER_CONTACT_US_ADDRESS)%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '%kernel.project_dir%/src/Controller'
        public: true
        autowire: true
        tags: ['controller.service_arguments']
