doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_pgsql
                host: '%env(DATABASE_HOST)%'
                port: '%env(DATABASE_PORT)%'
                dbname: '%env(DATABASE_NAME)%'
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                charset: UTF8
                logging: '%kernel.debug%'
                server_version: '11.0'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity'
                alias: GedmoLoggable # (optional) it will default to the name set for the mapping
                is_bundle: false
            Common:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Common/Entity'
                prefix: 'App\Common\Entity'
                alias: Common
            Grabber:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Grabber/Entity'
                prefix: 'App\Grabber\Entity'
                alias: Grabber
